#!/bin/bash
STRING1=$(~/git/wiki/profile/pl.sh)
STRING=$(echo $STRING1 | iconv -t ASCII//TRANSLIT)
if [ ${#STRING} -lt 16 ]; then
  PAD=$(( 17 -${#STRING} ))
  for i in `seq $PAD`; do
    echo -n "#"
  done
fi
echo -n $STRING
